seed: 1
savestring: "NDT2"

path_to_data: /n/home07/djimenezbeneto/lab/datasets/BCI/processed.data
path_to_model: /n/home07/djimenezbeneto/lab/models/BCI
checkpoint_dir: /n/home07/djimenezbeneto/lab/BCI/checkpoints
ft_dir: /n/home07/djimenezbeneto/lab/BCI/ft_models

checkpoint_epoch: None

eval_len: None
eval_batch_size: 64

generation:
  max_new_tokens: 16
  do_sample: False

