seed: 1
savestring: lora.alpha.0
data_file: processed.data

data_dir: /n/home07/djimenezbeneto/lab/datasets/BCI/competitionData
model_dir: /n/home07/djimenezbeneto/lab/models/BCI
checkpoint_dir: /n/home07/djimenezbeneto/lab/BCI/checkpoints
ft_dir: /n/home07/djimenezbeneto/lab/BCI/ft_models

checkpoint_epoch: 25

split: test
eval_len: null
eval_batch_size: 64

generation:
  max_new_tokens: 16
  do_sample: false

