seed: 1
savestring: "NDT2"

path_to_data: /n/home07/djimenezbeneto/lab/datasets/BCI/processed.data
path_to_model: /n/home07/djimenezbeneto/lab/models/BCI
checkpoint_dir: /n/home07/djimenezbeneto/lab/BCI/checkpoints
ft_dir: /n/home07/djimenezbeneto/lab/BCI/ft_models
log_dir: /n/home07/djimenezbeneto/lab/BCI/logs

trainer:
  num_epochs: 25
  save_epochs: [1,2,5,10,15,20]
  save_every: null
  train_len: null     # null to use whole set
  test_len: null      # null to use whole set
  test_batch_size: 64
  train_batch_size: 64

optimizer:
  lr: 1e-4
  wd: 0.1
  warmup_ratio: 0.1

lora:
  r: 8
  alpha: 0
  dropout: 0.5


bci: include:configs/default_bci_config.yaml  # this could be null as the bci model already loads this default config
# bci: null