
# Poisson MM
use_lograte: true     # true to treat the model predicitons as logrates (thus exponentiate before PoissonNLL)

loss: 
  type: ctc       # ctc or poisson
  reduction: sum  # sum, mean or none
  