seed: 1
savestring: poisson-pretrain  
data_file: processed.data

model_dir: null  # pretrained model to load to continue pretraining, null to start from scratch
data_dir: /n/home07/djimenezbeneto/lab/datasets/BCI/competitionData
checkpoint_dir: /n/home07/djimenezbeneto/lab/BCI/checkpoints
pt_dir: /n/home07/djimenezbeneto/lab/BCI/pt_models
log_dir: /n/home07/djimenezbeneto/lab/BCI/logs


trainer:
  num_epochs: 400
  save_epochs: [1,50,100,200,300,390]
  save_every: null
  train_len: null     # null to use whole set
  test_len: null      # null to use whole set
  test_batch_size: 64
  train_batch_size: 64

optimizer:
  lr: 1.e-3
  wd: 0.0
  warmup_steps: 1000 

neural_config: include:configs/default_neural_config.yaml
neural_pretrainer: include:configs/default_neural_pretrainer_config.yaml