# Data 
n_channels: 256
n_blocks: 25
n_dates: 24
max_spikes: 60
context_forward: 15
context_backward: 30

# Init
spike_log_init: true
fixup_init: true

# Neural Encoder Architecture
embed_mult: 1
embed_mode: "embed"
embed_bias: false
embed_gate: false
embed_act: "sigmoid"
embed_context: false

use_scalenorm: false
n_layers: 2
n_heads: 2
hidden_act: "silu"
attention_bias: false
mlp_bias: false


# Neural encoder regularization
embed_dropout: 0.5
layers_dropout: 0.5

# Positional encoding
use_rope: false
rope_theta: 10000.0
max_T: 1024



