seed: 1
savestring: default_savestring
data_file: default_data
log_to_wandb: false
wandb_project: default_project

dirs: include:configs/default_dirs.yaml

load_pretrained: false

day_specific: true

eval:
  smoothing: 0
  save_data: false

masker_scheduler:
  active: false
  start: 60
  end: 100

trainer:
  num_epochs: 100
  save_epochs: []
  save_every: null
  train_len: null     # null to use whole set
  test_len: null      # null to use whole set
  test_batch_size: 128
  train_batch_size: 64

optimizer:
  lr: 1.e-3
  wd: 5.e-5
  warmup_epochs: 0
  eps: 1.e-8
  scheduler: cosine # linear

neural_encoder: include:configs/default_neural_encoder_config.yaml
neural_pretrainer: include:configs/default_neural_pretrainer_config.yaml