model_class: iTransformer

# List of masks
masker: 
  neuron:
    active: true         
    mode: neuron        # masking mode
    ratio: 0.1          # ratio of data to predict
    zero_ratio: 1.0     # of the data to predict, ratio of zeroed out
    random_ratio: 1.0   # of the not zeroed, ratio of randomly replaced
    expand_prob: 0.0    # probability of expanding the mask in ``temporal`` mode
    max_timespan: 1     # max span of mask if expanded
    regions: null       # brain regions to mask in ``region`` mode
    channels: null      # neurons to mask in ``co-smooth`` mode
  temporal: 
    active: true      
    mode: temporal      # masking mode
    ratio: 0.1          # ratio of data to predict
    zero_ratio: 1.0     # of the data to predict, ratio of zeroed out
    random_ratio: 1.0   # of the not zeroed, ratio of randomly replaced
    expand_prob: 0.0    # probability of expanding the mask in ``temporal`` mode
    max_timespan: 1     # max span of mask if expanded
    regions: null       # brain regions to mask in ``region`` mode
    channels: null      # neurons to mask in ``co-smooth`` mode


encoder:
  from_pt: null

  embedder:
    mode: mlp
    activation: relu
    dropout: 0.2
    n_heads: 4
    hidden_size: 128
    n_layers: 4
    max_n_bins: 100

  hidden_size: 768
  activation: relu
  bias: true
  dropout: 0.4
  n_heads: 8
  n_layers: 5
  max_n_channels: 1500 # 0 to skip channel embeddings
  embed_region: true
  embed_depth: true
  regions: null


decoder:
  from_pt: null
  mlp_decoder: true
  activation: relu
  use_cls: true
