# Project to llama hidden space
softmax: False      # wether to convert logits to probabilities
temperature: 10     # temperature for softmax
input_size: 41      # must be equal to size of phonemes vocabulary (including SIL and BLANK)
inter_size: 2048    # size of the intermediate layer in the adapter MLP
act: tanh           # activation function in the adapter MLP
bias: True

loss_reduction: mean


