data_file: processed2.data  # name of preprocessed data file

tokenizer_dir: /n/home07/djimenezbeneto/lab/models/BCI                  # load tokenizer from here
data_dir: /n/home07/djimenezbeneto/lab/datasets/BCI/competitionData     # load data from here

splits: ["train","test","competitionHoldOut"]  # which data to load
feature: "tx1"            # feature to extract
prompt: ""                # add prompt before sentence 
zscore: true              # normalize blocks

