seed: 1

savestring: test
wandb_project: test
log_to_wandb: false

verbosity: 0

# Logging directories
dirs:
  checkpoint_dir: /home/gridsan/dbeneto/TFG/BCI/pt_checkpoints  # save model state dicts (todo optimizer states)
  log_dir: /home/gridsan/dbeneto/TFG/BCI/pt_logs  # save tensorboard logs


# Training configuration
training:
  num_epochs: 1000
  train_batch_size: 16
  test_batch_size: 16   
  shuffle_test_dataloader: true    # Shuffle test dataloader between epochs

  save_every: 1500 # Save checkpoint
  eval_every: 500  # Eval model



model: include:configs/patchtst.yaml

data:
  dataset_class: ssl

  hf_dataset_name: null
  json_dataset_name: null
  
  train_name: train   # name of the train split in the raw datasete
  test_name: test     # name of the test split in the raw datasete
  train_len: null     # used length of the train dataset. null to use all
  test_len: null      # used length of the test dataset. null to use all

  data_load: file # file/speechbci
  data_file: /home/gridsan/dbeneto/MAML-Soljacic_shared/BCI/data/ibl_choice_0.pth

  dataset_dir: /home/gridsan/dbeneto/MAML-Soljacic_shared/BCI/data/competitionData
  zscore: false
  features: ["tx1"]
  date_idxs: null
  
method:

  model_kwargs:
    method_name: mlm

    log_input: true
    loss: poisson_nll # poisson_nll/mse(todo)

  dataset_kwargs: {}


  dataloader_kwargs:
    pad_dict:
      spikes:
        dim: 0
        side: left
        value: 0
        truncate: null
        min_length: null
      spikes_mask:
        dim: 0
        side: left
        value: 0
        truncate: null
        min_length: null
      spikes_timestamp:
        dim: 0
        side: left
        value: 0
        truncate: null
        min_length: null

  metric_kwargs: {}

optimizer:
  gradient_accumulation_steps: 1
  lr: 1.e-4
  wd: 0.01
  eps: 1.e-8
  warmup_pct: 0.15 # cosine/linear
  gamma: 0.95     # step
  div_factor: 10  # cosine
  scheduler: cosine # step/cosine/linear
