seed: 1

savestring: test
wandb_project: test
log_to_wandb: false

verbosity: 0

# Logging directories
dirs:
  checkpoint_dir: /home/gridsan/dbeneto/TFG/BCI/pt_checkpoints  # save model state dicts (todo optimizer states)
  log_dir: /home/gridsan/dbeneto/TFG/BCI/pt_logs  # save tensorboard logs


# Training configuration
training:
  num_epochs: 75
  train_batch_size: 1
  test_batch_size: 1      
  shuffle_test_dataloader: false    # Shuffle test dataloader between epochs
  drop_last_test_dataloader: false   # Drop last batch to ensure same batch size
  drop_last_train_dataloader: false   # Drop last batch to ensure same batch size
  save_every: 100  # Save checkpoint
  eval_every: 100  # Eval model

model: include:configs/ndt1.yaml

data:
  dataset_class: decoding

  hf_dataset_name: null
  json_dataset_name: null

  train_name: train   # name of the train split in the raw datasete
  test_name: test     # name of the test split in the raw datasete
  train_len: null     # used length of the train dataset. null to use all
  test_len: null      # used length of the test dataset. null to use all

  data_load: speechbci
  data_dir: /home/gridsan/dbeneto/MAML-Soljacic_shared/BCI/data/competitionData
  zscore_block: True
  zscore_day: True
  vocab_file: vocab.json
  date_idxs: null

method:

  model_kwargs:
    method_name: ctc   
    vocab_size: 41
    blank_id: 0
    zero_infinity: true
  
  dataset_kwargs:
    targets_name: phonemes_idx
    batch_size: 1

  dataloader_kwargs:
    pad_dict:
      spikes:
        dim: 0
        side: right
        value: 0
        truncate: null
        min_length: null
      spikes_mask:
        dim: 0
        side: right
        value: 0
        truncate: null
        min_length: null
      spikes_timestamp:
        dim: 0
        side: right
        value: 0
        truncate: null
        min_length: null
      targets:
        dim: 0
        side: right
        value: 0
        truncate: null
        min_length: null
      targets_mask:
        dim: 0
        side: right
        value: 0
        truncate: null
        min_length: null

  metric_kwargs:
    n_print: 1

optimizer:
  gradient_accumulation_steps: 1
  lr: 1.e-3
  wd: 5.e-5
  eps: 1.e-8
  warmup_pct: 0.0 # cosine/linear
  gamma: 0.95     # step
  div_factor: 25  # cosine
  scheduler: cosine # step/cosine/linear
